name: Check disk space
on:
  - push
  - schedule:
    - cron: 36 19 * * thu
jobs:
  disk-space:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - run: df -h /
      - run: du -chxd 5 / 2>/dev/null | sort -rh | head -n 100
